apiVersion: v2
name: ingress-nginx
description: A Helm chart for Nginx Ingress Controller and Let's Encrypt SSL
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nginx
  - ingress
  - controller
  - letsencrypt
  - ssl
home: https://yjhome.kro.kr
maintainers:
  - name: pyj
    email: piwhyjey@gmail.com
dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cert-manager
    version: "1.13.2"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
